spring.application.name=config-server
server.port=8888
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
spring.cloud.config.server.native.search-locations=classpath:/configs
spring.profiles.active=native
